### PR TITLE
Add toggle command for entire UI

### PR DESCRIPTION
**Pull request by Sharkiiie**
This allows the debugger to be used on a live server, and / or only by those with ACE Perms.
(Requested in issue #3)

### CODE REVIEW

**Comment by Sharkiiie** [comment]
Also some linting :)

**Comment by JenMaki** [comment]
Hey, could you lint the project with the original convention?
- White spaces in the CSS and JS files.
- White space around the string concatenations in the Lua files.

It looks great otherwise!

**Comment by Sharkiiie** [comment]
Just to confirm, you'd like me to remove the spaces in the string concatenations, and use tabs instead of spaces in the CSS and JS files?

**Comment by JenMaki** [comment]
Correct.

**Comment by Sharkiiie** [comment]
It will hurt my soul a bit, but I'll do it as soon as I have some time in the next day or so.

**Comment by Sharkiiie** [comment]
Life got in the way so it took a bit longer.
Lemme know if there's any more changes you'd like.

**Comment by JenMaki** [comment]
Looks good, great job!

**Pull request merged**
